/**
 * Strata — Infrastructure-as-Code export
 * ------------------------------------------------
 * The mirror of `iac.ts`: turns the in-app `InfrastructureGraph` into
 * **CloudFormation** (JSON / YAML) and **Terraform** (HCL).
 *
 * Honest framing (see specs/flow-3-export-iac.md):
 *   Import is lossy — we normalise to our model, drop unmapped types, and keep
 *   only registry-known config. So export is a **scaffold a human finishes**,
 *   not faithful round-trip. Generated IaC has the right resource *types* and
 *   *dependencies*, but property names follow Strata's config model (not the
 *   full provider schema), and required provider fields we don't model are
 *   emitted as `TODO` placeholders and tallied in the `ExportReport`.
 *
 * Join keys (reverse of the importer):
 *  - CloudFormation: a service's registry `cfnType` IS the resource `Type`.
 *  - Terraform: the registry `serviceId` maps to a canonical `aws_*` type via
 *    the inverse of `TF_TYPE_TO_SERVICE_ID` (first-listed wins; see below).
 *
 * Pure and deterministic: no network, no auth, no Date/Math.random. Resources
 * are processed in a stable id-sorted order so output is byte-stable for tests.
 */
import yaml from "js-yaml";
import type { InfrastructureGraph, ResourceInstance } from "./model";
import { getService } from "./registry";
import { TF_TYPE_TO_SERVICE_ID } from "./iac";

export type ExportFormat = "cloudformation-json" | "cloudformation-yaml" | "terraform";

/** Coverage/honesty report — mirrors `IacImportResult`'s shape. */
export interface ExportReport {
  /** Number of resources emitted. */
  exported: number;
  /**
   * Of `exported`, how many were re-emitted **verbatim** from a captured
   * `raw` source (faithful round-trip) vs. scaffolded from Strata's model.
   * `exported - faithful` resources are scaffolds the user must finish.
   */
  faithful: number;
  /** Resources omitted because the registry has no target type for them. */
  skipped: { id: string; serviceId: string; reason: string }[];
  /** Required provider fields we don't model, emitted as placeholders. */
  todos: { address: string; field: string }[];
  /** Non-fatal notes surfaced to the user. */
  warnings: string[];
}

const HEADER_NOTE =
  "Generated by Strata. This is a scaffold, not deploy-ready IaC: property names " +
  "follow Strata's model and TODO markers flag fields you must complete.";

/**
 * serviceId → canonical Terraform type. The import table is many-to-one
 * (e.g. aws_lb / aws_alb / aws_elb all map to "elastic-load-balancer"), so the
 * inverse keeps the FIRST-listed Terraform type as the canonical export target.
 */
export const SERVICE_ID_TO_TF_TYPE: Record<string, string> = (() => {
  const inv: Record<string, string> = {};
  for (const [tfType, serviceId] of Object.entries(TF_TYPE_TO_SERVICE_ID)) {
    if (!(serviceId in inv)) inv[serviceId] = tfType;
  }
  return inv;
})();

// ---------------------------------------------------------------------------
// Shared planning
// ---------------------------------------------------------------------------

/** A resource resolved to its export identifiers, before serialization. */
interface PlannedResource {
  resource: ResourceInstance;
  /** Sanitised CloudFormation logical id (alphanumeric, unique). */
  logicalId: string;
  /** Sanitised Terraform resource name (valid identifier, unique). */
  tfName: string;
}

/** Sanitise to a CloudFormation logical id: alphanumeric, leading letter. */
function sanitizeLogicalId(raw: string): string {
  const cleaned = raw.replace(/[^A-Za-z0-9]/g, "");
  if (!cleaned) return "Resource";
  return /^[A-Za-z]/.test(cleaned) ? cleaned : `R${cleaned}`;
}

/** Sanitise to a Terraform identifier: [A-Za-z0-9_-], leading letter/underscore. */
function sanitizeTfName(raw: string): string {
  const cleaned = raw.replace(/[^A-Za-z0-9_-]/g, "_");
  if (!cleaned) return "resource";
  return /^[A-Za-z_]/.test(cleaned) ? cleaned : `_${cleaned}`;
}

/** Make `base` unique within `used`, appending a numeric suffix if needed. */
function unique(base: string, used: Set<string>): string {
  let candidate = base;
  let n = 2;
  while (used.has(candidate)) candidate = `${base}${n++}`;
  used.add(candidate);
  return candidate;
}

/** Assign stable, unique export identifiers to every resource (id-sorted). */
function planResources(graph: InfrastructureGraph): PlannedResource[] {
  const sorted = [...graph.resources].sort((a, b) => a.id.localeCompare(b.id));
  const cfnUsed = new Set<string>();
  const tfUsed = new Set<string>();
  return sorted.map((resource) => ({
    resource,
    logicalId: unique(sanitizeLogicalId(resource.name || resource.id), cfnUsed),
    tfName: unique(sanitizeTfName(resource.name || resource.id), tfUsed),
  }));
}

/**
 * Outgoing dependency target ids for a resource: its containment parent plus
 * every relationship it originates, restricted to resources present in `ids`.
 * (Typed edge *kinds* are intentionally coarsened to dependencies — a
 * documented lossy delta; structure is preserved, semantics are not.)
 */
function dependencyTargets(
  resource: ResourceInstance,
  graph: InfrastructureGraph,
  ids: Set<string>,
): string[] {
  const targets = new Set<string>();
  if (resource.parentId && ids.has(resource.parentId) && resource.parentId !== resource.id) {
    targets.add(resource.parentId);
  }
  for (const rel of graph.relationships) {
    if (rel.from === resource.id && ids.has(rel.to) && rel.to !== resource.id) {
      targets.add(rel.to);
    }
  }
  return [...targets].sort();
}

/** Known config (under registry keys) + a `report` side-effect for missing required fields. */
function knownConfig(
  resource: ResourceInstance,
  address: string,
  report: ExportReport,
): { values: Record<string, unknown>; todoKeys: string[] } {
  const svc = getService(resource.serviceId);
  const values: Record<string, unknown> = {};
  const todoKeys: string[] = [];
  if (!svc) return { values, todoKeys };
  for (const field of svc.configFields) {
    const has = Object.prototype.hasOwnProperty.call(resource.config, field.key);
    if (has && resource.config[field.key] !== "" && resource.config[field.key] !== undefined) {
      values[field.key] = resource.config[field.key];
    } else if (field.required) {
      todoKeys.push(field.key);
      report.todos.push({ address, field: field.key });
    }
  }
  return { values, todoKeys };
}

function emptyReport(): ExportReport {
  return { exported: 0, faithful: 0, skipped: [], todos: [], warnings: [] };
}

/** An extra CloudFormation resource a transform asks the exporter to emit. */
interface CfnAuxResource {
  /** Appended to the primary logical id to form the aux logical id. */
  logicalSuffix: string;
  type: string;
  properties: Record<string, unknown>;
}

/** Properties for the primary resource, plus any auxiliary resources. */
interface CfnScaffold {
  properties: Record<string, unknown>;
  auxiliary?: CfnAuxResource[];
}

/**
 * Per-service CloudFormation property transformers (scaffold path only).
 *
 * A flat key-rename (`cfnPropertyNames`) can only relabel a key — it cannot
 * change a value's *shape* or split config across *multiple* resources. Some
 * services need exactly that to emit valid CloudFormation, so they register a
 * transformer here. It receives the resource's known config (registry keys) and
 * returns real CFN `Properties` plus any auxiliary resources to emit alongside
 * (each gets a `DependsOn` back to the primary).
 *
 * Only the scaffold path consults this map; a faithfully-captured `raw` source
 * is always re-emitted verbatim and never transformed.
 */
const CFN_TRANSFORMS: Record<string, (config: Record<string, unknown>) => CfnScaffold> = {
  // S3: versioning/encryption are nested objects and Block Public Access is a
  // SEPARATE AWS::S3::BucketPublicAccessBlock resource — none expressible as a
  // flat rename. (`storageClass` is object/lifecycle-level, not a bucket prop,
  // so it is intentionally dropped from the scaffold.)
  "s3-bucket": (config) => {
    const properties: Record<string, unknown> = {};
    if (typeof config.bucketName === "string" && config.bucketName) {
      properties.BucketName = config.bucketName;
    }
    if (config.versioning !== undefined) {
      properties.VersioningConfiguration = { Status: config.versioning ? "Enabled" : "Suspended" };
    }
    if (typeof config.encryption === "string" && config.encryption) {
      const algo =
        config.encryption === "SSE-KMS"
          ? "aws:kms"
          : config.encryption === "DSSE-KMS"
            ? "aws:kms:dsse"
            : "AES256";
      properties.BucketEncryption = {
        ServerSideEncryptionConfiguration: [
          { ServerSideEncryptionByDefault: { SSEAlgorithm: algo } },
        ],
      };
    }
    const auxiliary: CfnAuxResource[] = [];
    if (config.blockPublicAccess !== undefined) {
      const on = config.blockPublicAccess === true;
      auxiliary.push({
        logicalSuffix: "PublicAccessBlock",
        type: "AWS::S3::BucketPublicAccessBlock",
        properties: {
          Bucket: { Ref: "__PRIMARY__" },
          PublicAccessBlockConfiguration: {
            BlockPublicAcls: on,
            BlockPublicPolicy: on,
            IgnorePublicAcls: on,
            RestrictPublicBuckets: on,
          },
        },
      });
    }
    return { properties, auxiliary };
  },
};

// ---------------------------------------------------------------------------
// CloudFormation
// ---------------------------------------------------------------------------

export interface CloudFormationExport {
  json: string;
  yaml: string;
  report: ExportReport;
}

export function exportCloudFormation(graph: InfrastructureGraph): CloudFormationExport {
  const report = emptyReport();
  const planned = planResources(graph);
  const ids = new Set(planned.map((p) => p.resource.id));
  const logicalById = new Map(planned.map((p) => [p.resource.id, p.logicalId]));

  const resources: Record<string, unknown> = {};
  const usedLogical = new Set(planned.map((p) => p.logicalId));
  for (const { resource, logicalId } of planned) {
    const svc = getService(resource.serviceId);
    // A captured CloudFormation `raw` source re-emits faithfully even if the
    // registry entry has since lost its cfnType, so resolve the emitted Type
    // from `raw` first, falling back to the registry.
    const faithfulRaw = resource.raw?.format === "cloudformation" ? resource.raw : undefined;
    const cfnType = faithfulRaw?.type ?? svc?.cfnType;
    if (!cfnType) {
      report.skipped.push({
        id: resource.id,
        serviceId: resource.serviceId,
        reason: "no CloudFormation type in the registry",
      });
      continue;
    }

    const computedDependsOn = dependencyTargets(resource, graph, ids)
      .map((id) => logicalById.get(id))
      .filter((v): v is string => Boolean(v));

    let entry: Record<string, unknown>;
    if (faithfulRaw) {
      // Faithful path: re-emit the verbatim Type + Properties (intrinsics intact).
      entry = { Type: faithfulRaw.type };
      if (faithfulRaw.properties && Object.keys(faithfulRaw.properties).length > 0) {
        entry.Properties = faithfulRaw.properties;
      }
      if (faithfulRaw.condition) entry.Condition = faithfulRaw.condition;
      if (faithfulRaw.metadata) entry.Metadata = faithfulRaw.metadata;
      // Prefer the original DependsOn; fall back to the graph-derived deps.
      const dependsOn = faithfulRaw.dependsOn?.length ? faithfulRaw.dependsOn : computedDependsOn;
      if (dependsOn.length > 0) entry.DependsOn = dependsOn;
      report.faithful++;
    } else {
      // Scaffold path: a registered transform builds real CFN Properties (and
      // any auxiliary resources); otherwise property names follow Strata's model
      // with the optional cfnPropertyNames map applied. Required-missing fields
      // become TODOs either way.
      const { values, todoKeys } = knownConfig(resource, logicalId, report);
      const transform = CFN_TRANSFORMS[resource.serviceId];
      const scaffold = transform ? transform(values) : undefined;
      const properties: Record<string, unknown> = scaffold
        ? { ...scaffold.properties }
        : { ...applyPropertyNames(svc, values) };
      for (const key of todoKeys) {
        properties[svc?.cfnPropertyNames?.[key] ?? key] = "TODO: required — set this value";
      }
      entry = { Type: cfnType };
      if (Object.keys(properties).length > 0) entry.Properties = properties;
      if (computedDependsOn.length > 0) entry.DependsOn = computedDependsOn;

      // Emit any auxiliary resources, substituting the primary's logical id for
      // the `__PRIMARY__` Ref placeholder and wiring a DependsOn back to it.
      for (const aux of scaffold?.auxiliary ?? []) {
        const auxId = unique(`${logicalId}${aux.logicalSuffix}`, usedLogical);
        const auxProps = JSON.parse(
          JSON.stringify(aux.properties).replace(/__PRIMARY__/g, logicalId),
        ) as Record<string, unknown>;
        resources[auxId] = { Type: aux.type, Properties: auxProps, DependsOn: [logicalId] };
        report.exported++;
      }
    }

    resources[logicalId] = entry;
    report.exported++;
  }

  if (report.exported === 0) {
    report.warnings.push("No resources could be exported to CloudFormation.");
  }
  if (report.skipped.length > 0) {
    report.warnings.push(`${report.skipped.length} resource(s) skipped (no CloudFormation type).`);
  }
  const scaffolded = report.exported - report.faithful;
  if (report.faithful > 0 && scaffolded > 0) {
    report.warnings.push(
      `${report.faithful} resource(s) re-emitted faithfully; ${scaffolded} scaffolded from Strata's model.`,
    );
  }

  // Re-emit captured template sections (Parameters/Outputs/…) for faithful
  // round-trip; otherwise fall back to a minimal scaffold header.
  const src = graph.iacSource?.format === "cloudformation" ? graph.iacSource : undefined;
  const template: Record<string, unknown> = {
    AWSTemplateFormatVersion: src?.formatVersion ?? "2010-09-09",
    Description: src?.description ?? HEADER_NOTE,
  };
  if (src?.parameters) template.Parameters = src.parameters;
  if (src?.mappings) template.Mappings = src.mappings;
  if (src?.conditions) template.Conditions = src.conditions;
  if (src?.metadata) template.Metadata = src.metadata;
  if (src?.transform !== undefined) template.Transform = src.transform;
  template.Resources = resources;
  if (src?.outputs) template.Outputs = src.outputs;

  return {
    json: JSON.stringify(template, null, 2),
    yaml: yaml.dump(template, { lineWidth: 120, noRefs: true }),
    report,
  };
}

/**
 * Apply a service's optional `cfnPropertyNames` map to rename Strata config
 * keys to their provider-native property names (CFN Stage 3 / multi-cloud).
 * Keys without a mapping pass through unchanged.
 */
function applyPropertyNames(
  svc: ReturnType<typeof getService>,
  values: Record<string, unknown>,
): Record<string, unknown> {
  const map = svc?.cfnPropertyNames;
  if (!map) return values;
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(values)) out[map[k] ?? k] = v;
  return out;
}

// ---------------------------------------------------------------------------
// Terraform (HCL)
// ---------------------------------------------------------------------------

export interface TerraformExport {
  hcl: string;
  report: ExportReport;
}

/** True if `k` is a bare HCL identifier (else it must be quoted as a key). */
function isBareKey(k: string): boolean {
  return /^[A-Za-z_][A-Za-z0-9_-]*$/.test(k);
}

/** Render a value as an HCL literal (strings quoted, nested lists/maps indented). */
function hclValue(value: unknown, indent: string): string {
  if (value === null || value === undefined) return "null";
  if (typeof value === "string") return JSON.stringify(value);
  if (typeof value === "number" || typeof value === "boolean") return String(value);
  if (Array.isArray(value)) {
    if (value.length === 0) return "[]";
    const inner = value.map((v) => `${indent}  ${hclValue(v, `${indent}  `)}`).join(",\n");
    return `[\n${inner},\n${indent}]`;
  }
  if (typeof value === "object") {
    const entries = Object.entries(value as Record<string, unknown>);
    if (entries.length === 0) return "{}";
    const inner = entries
      .map(([k, v]) => {
        const key = isBareKey(k) ? k : JSON.stringify(k);
        return `${indent}  ${key} = ${hclValue(v, `${indent}  `)}`;
      })
      .join("\n");
    return `{\n${inner}\n${indent}}`;
  }
  return JSON.stringify(String(value));
}

export function exportTerraform(
  graph: InfrastructureGraph,
  serviceIdToTfType: Record<string, string> = SERVICE_ID_TO_TF_TYPE,
): TerraformExport {
  const report = emptyReport();
  const planned = planResources(graph);
  const ids = new Set(planned.map((p) => p.resource.id));
  const addressById = new Map<string, string>();
  for (const p of planned) {
    const tfType = serviceIdToTfType[p.resource.serviceId];
    if (tfType) addressById.set(p.resource.id, `${tfType}.${p.tfName}`);
  }

  const blocks: string[] = [];
  for (const { resource, tfName } of planned) {
    const tfType = serviceIdToTfType[resource.serviceId];
    if (!tfType) {
      report.skipped.push({
        id: resource.id,
        serviceId: resource.serviceId,
        reason: "no Terraform type mapping in the registry",
      });
      continue;
    }
    const address = `${tfType}.${tfName}`;
    const { values, todoKeys } = knownConfig(resource, address, report);

    const lines: string[] = [`resource "${tfType}" "${tfName}" {`];
    for (const [key, value] of Object.entries(values)) {
      const k = isBareKey(key) ? key : JSON.stringify(key);
      lines.push(`  ${k} = ${hclValue(value, "  ")}`);
    }
    for (const key of todoKeys) lines.push(`  # TODO: set required field "${key}"`);
    const deps = dependencyTargets(resource, graph, ids)
      .map((id) => addressById.get(id))
      .filter((v): v is string => Boolean(v));
    if (deps.length > 0) lines.push(`  depends_on = [${deps.join(", ")}]`);
    lines.push("}");
    blocks.push(lines.join("\n"));
    report.exported++;
  }

  if (report.exported === 0) report.warnings.push("No resources could be exported to Terraform.");
  if (report.skipped.length > 0) {
    report.warnings.push(`${report.skipped.length} resource(s) skipped (no Terraform mapping).`);
  }

  const header = `# ${HEADER_NOTE}\n`;
  return { hcl: report.exported > 0 ? `${header}\n${blocks.join("\n\n")}\n` : header, report };
}

// ---------------------------------------------------------------------------
// Convenience
// ---------------------------------------------------------------------------

export interface IacExportResult {
  content: string;
  /** Suggested download filename. */
  filename: string;
  report: ExportReport;
}

/** Export to the chosen format, returning content + filename + report. */
export function exportIaC(graph: InfrastructureGraph, format: ExportFormat): IacExportResult {
  switch (format) {
    case "cloudformation-json": {
      const { json, report } = exportCloudFormation(graph);
      return { content: json, filename: "strata-template.json", report };
    }
    case "cloudformation-yaml": {
      const { yaml: y, report } = exportCloudFormation(graph);
      return { content: y, filename: "strata-template.yaml", report };
    }
    case "terraform": {
      const { hcl, report } = exportTerraform(graph);
      return { content: hcl, filename: "strata.tf", report };
    }
  }
}
