/**
 * Azure Networking service catalog.
 * Virtual Network and Subnet are containers; the rest are regional resources.
 * Mirrors the AWS networking catalog shape (see src/aws/services/networking.ts).
 */
import type { ServiceDefinition } from "../../aws/types";

const networking: ServiceDefinition[] = [
  {
    id: "azure-vnet",
    name: "Virtual Network",
    fullName: "Azure Virtual Network",
    abbreviation: "VNet",
    provider: "azure",
    category: "networking",
    description: "An isolated virtual network for securely running Azure resources.",
    icon: "🏛️",
    scope: "region",
    isContainer: true,
    nativeType: "Microsoft.Network/virtualNetworks",
    keywords: ["vnet", "virtual network", "network", "cidr"],
    configFields: [
      {
        key: "addressSpace",
        label: "Address Space",
        type: "cidr",
        placeholder: "10.0.0.0/16",
        default: "10.0.0.0/16",
        required: true,
      },
      { key: "dnsServers", label: "DNS Servers", type: "text", placeholder: "168.63.129.16" },
      { key: "tags", label: "Tags", type: "tags" },
    ],
    commonConnections: [
      { to: "azure-subnet", relationship: "contains", description: "VNet contains subnets" },
      { to: "azure-vnet", relationship: "peers_with" },
    ],
  },
  {
    id: "azure-subnet",
    name: "Subnet",
    fullName: "Azure Virtual Network Subnet",
    provider: "azure",
    category: "networking",
    description: "A segment of a VNet's address space that hosts resources.",
    icon: "🟦",
    scope: "region",
    isContainer: true,
    nativeType: "Microsoft.Network/virtualNetworks/subnets",
    keywords: ["subnet", "vnet", "network", "segment"],
    configFields: [
      {
        key: "addressPrefix",
        label: "Address Prefix",
        type: "cidr",
        placeholder: "10.0.1.0/24",
        default: "10.0.1.0/24",
        required: true,
      },
      {
        key: "serviceEndpoints",
        label: "Service Endpoints",
        type: "text",
        placeholder: "Microsoft.Storage",
      },
    ],
    commonConnections: [
      { to: "azure-nsg", relationship: "attached_to" },
      { to: "azure-route-table", relationship: "attached_to" },
    ],
  },
  {
    id: "azure-nsg",
    name: "NSG",
    fullName: "Azure Network Security Group",
    abbreviation: "NSG",
    provider: "azure",
    category: "networking",
    description: "A stateful firewall of allow/deny rules for subnets and NICs.",
    icon: "🧱",
    scope: "region",
    nativeType: "Microsoft.Network/networkSecurityGroups",
    keywords: ["nsg", "network security group", "firewall", "rules"],
    configFields: [
      {
        key: "inboundRules",
        label: "Inbound Rules",
        type: "text",
        placeholder: "Allow TCP 443 from Internet",
      },
      { key: "outboundRules", label: "Outbound Rules", type: "text", placeholder: "Allow all" },
    ],
    commonConnections: [
      { to: "azure-subnet", relationship: "attached_to" },
      { to: "azure-nsg", relationship: "allows" },
    ],
  },
  {
    id: "azure-load-balancer",
    name: "Load Balancer",
    fullName: "Azure Load Balancer",
    abbreviation: "LB",
    provider: "azure",
    category: "networking",
    description: "Layer-4 (TCP/UDP) load balancing across backend pool members.",
    icon: "⚖️",
    scope: "region",
    nativeType: "Microsoft.Network/loadBalancers",
    keywords: ["load balancer", "lb", "layer 4", "tcp"],
    configFields: [
      {
        key: "sku",
        label: "SKU",
        type: "select",
        default: "Standard",
        options: [
          { value: "Basic", label: "Basic" },
          { value: "Standard", label: "Standard" },
        ],
      },
      {
        key: "type",
        label: "Type",
        type: "select",
        default: "Public",
        options: [
          { value: "Public", label: "Public" },
          { value: "Internal", label: "Internal" },
        ],
      },
    ],
    commonConnections: [
      { to: "azure-vmss", relationship: "targets" },
      { to: "azure-vm", relationship: "targets" },
      { to: "azure-public-ip", relationship: "attached_to" },
    ],
  },
  {
    id: "azure-app-gateway",
    name: "App Gateway",
    fullName: "Azure Application Gateway",
    abbreviation: "AGW",
    provider: "azure",
    category: "networking",
    description: "Layer-7 load balancer with routing, TLS and WAF capabilities.",
    icon: "🚪",
    scope: "region",
    nativeType: "Microsoft.Network/applicationGateways",
    keywords: ["application gateway", "agw", "layer 7", "waf", "ingress"],
    configFields: [
      {
        key: "sku",
        label: "SKU",
        type: "select",
        default: "Standard_v2",
        options: [
          { value: "Standard_v2", label: "Standard_v2" },
          { value: "WAF_v2", label: "WAF_v2" },
        ],
      },
      { key: "capacity", label: "Instance Count", type: "number", default: 2 },
      { key: "enableWaf", label: "Enable WAF", type: "boolean", default: false },
    ],
    commonConnections: [
      { to: "azure-app-service", relationship: "targets" },
      { to: "azure-public-ip", relationship: "attached_to" },
      { to: "azure-subnet", relationship: "attached_to" },
    ],
  },
  {
    id: "azure-public-ip",
    name: "Public IP",
    fullName: "Azure Public IP Address",
    provider: "azure",
    category: "networking",
    description: "A static or dynamic public IPv4/IPv6 address for inbound access.",
    icon: "🌍",
    scope: "region",
    nativeType: "Microsoft.Network/publicIPAddresses",
    keywords: ["public ip", "pip", "address", "ingress"],
    configFields: [
      {
        key: "allocationMethod",
        label: "Allocation",
        type: "select",
        default: "Static",
        options: [
          { value: "Static", label: "Static" },
          { value: "Dynamic", label: "Dynamic" },
        ],
      },
      {
        key: "sku",
        label: "SKU",
        type: "select",
        default: "Standard",
        options: [
          { value: "Basic", label: "Basic" },
          { value: "Standard", label: "Standard" },
        ],
      },
    ],
    commonConnections: [{ to: "azure-load-balancer", relationship: "attached_to" }],
  },
  {
    id: "azure-route-table",
    name: "Route Table",
    fullName: "Azure Route Table (User Defined Routes)",
    provider: "azure",
    category: "networking",
    description: "User-defined routes controlling traffic flow for associated subnets.",
    icon: "🧭",
    scope: "region",
    nativeType: "Microsoft.Network/routeTables",
    keywords: ["route table", "udr", "routing", "network"],
    configFields: [
      {
        key: "routes",
        label: "Routes",
        type: "text",
        placeholder: "0.0.0.0/0 -> VirtualAppliance",
      },
      {
        key: "disableBgpRoutePropagation",
        label: "Disable BGP Propagation",
        type: "boolean",
        default: false,
      },
    ],
    commonConnections: [{ to: "azure-subnet", relationship: "attached_to" }],
  },
  {
    id: "azure-dns-zone",
    name: "DNS Zone",
    fullName: "Azure DNS Zone",
    provider: "azure",
    category: "networking",
    description: "Hosts DNS records for a domain using Azure's name servers.",
    icon: "🧬",
    scope: "global",
    nativeType: "Microsoft.Network/dnsZones",
    keywords: ["dns", "zone", "domain", "records"],
    configFields: [
      {
        key: "zoneName",
        label: "Zone Name",
        type: "string",
        placeholder: "example.com",
        required: true,
      },
      {
        key: "zoneType",
        label: "Zone Type",
        type: "select",
        default: "Public",
        options: [
          { value: "Public", label: "Public" },
          { value: "Private", label: "Private" },
        ],
      },
    ],
    commonConnections: [
      { to: "azure-app-gateway", relationship: "routes_to" },
      { to: "azure-public-ip", relationship: "routes_to" },
    ],
  },
  {
    id: "azure-network-interface",
    name: "Network Interface",
    fullName: "Azure Network Interface",
    abbreviation: "NIC",
    provider: "azure",
    category: "networking",
    description: "A virtual NIC that connects a VM to a subnet, NSG and public IP.",
    icon: "🔌",
    scope: "resource-group",
    nativeType: "Microsoft.Network/networkInterfaces",
    keywords: ["network interface", "nic", "ip configuration", "vnic"],
    configFields: [
      {
        key: "privateIpAllocation",
        label: "Private IP Allocation",
        type: "select",
        default: "Dynamic",
        options: [
          { value: "Dynamic", label: "Dynamic" },
          { value: "Static", label: "Static" },
        ],
      },
      {
        key: "enableAcceleratedNetworking",
        label: "Accelerated Networking",
        type: "boolean",
        default: false,
      },
      { key: "enableIpForwarding", label: "IP Forwarding", type: "boolean", default: false },
    ],
    commonConnections: [
      { to: "azure-subnet", relationship: "attached_to" },
      { to: "azure-nsg", relationship: "attached_to" },
      { to: "azure-public-ip", relationship: "attached_to" },
      { to: "azure-vm", relationship: "attached_to" },
    ],
  },
  {
    id: "azure-private-endpoint",
    name: "Private Endpoint",
    fullName: "Azure Private Endpoint",
    abbreviation: "PE",
    provider: "azure",
    category: "networking",
    description: "A private IP in a subnet that connects privately to a PaaS service.",
    icon: "🔒",
    scope: "resource-group",
    nativeType: "Microsoft.Network/privateEndpoints",
    keywords: ["private endpoint", "private link", "private ip", "paas"],
    configFields: [
      {
        key: "groupIds",
        label: "Subresource (Group ID)",
        type: "string",
        placeholder: "blob",
      },
      {
        key: "manualConnection",
        label: "Manual Connection Approval",
        type: "boolean",
        default: false,
      },
    ],
    commonConnections: [
      { to: "azure-subnet", relationship: "attached_to" },
      { to: "azure-storage-account", relationship: "connects_to" },
      { to: "azure-sql-server", relationship: "connects_to" },
      { to: "azure-key-vault", relationship: "connects_to" },
    ],
  },
];

export default networking;
