/**
 * Machine Learning & AI service catalog.
 * Every entry is a `ServiceDefinition` and the array is the default export,
 * matching the structure of networking.ts.
 */
import type { ServiceDefinition } from "../types";

const aiMl: ServiceDefinition[] = [
  {
    id: "sagemaker",
    name: "SageMaker",
    fullName: "Amazon SageMaker",
    category: "ai-ml",
    description: "Fully managed platform to build, train, and deploy machine learning models.",
    icon: "🧠",
    scope: "region",
    cfnType: "AWS::SageMaker::Endpoint",
    arnPattern: "arn:aws:sagemaker:{region}:{account}:endpoint/{name}",
    keywords: ["sagemaker", "ml", "training", "model", "endpoint", "inference"],
    configFields: [
      {
        key: "instanceType",
        label: "Instance Type",
        type: "select",
        default: "ml.m5.xlarge",
        options: [
          { value: "ml.t3.medium", label: "ml.t3.medium" },
          { value: "ml.m5.xlarge", label: "ml.m5.xlarge" },
          { value: "ml.c5.2xlarge", label: "ml.c5.2xlarge" },
          { value: "ml.g4dn.xlarge", label: "ml.g4dn.xlarge" },
          { value: "ml.p3.2xlarge", label: "ml.p3.2xlarge" },
        ],
      },
      { key: "instanceCount", label: "Instance Count", type: "number", default: 1 },
      {
        key: "modelDataUrl",
        label: "Model Artifacts URL",
        type: "string",
        placeholder: "s3://bucket/model.tar.gz",
      },
    ],
    commonConnections: [
      {
        to: "s3-bucket",
        relationship: "reads_from",
        description: "Reads training data and model artifacts",
      },
      {
        to: "iam-role",
        relationship: "assumes",
        description: "Execution role for training and inference",
      },
      {
        to: "cloudwatch",
        relationship: "monitors",
        description: "Publishes training and endpoint metrics",
      },
      { to: "ecr", relationship: "reads_from", description: "Pulls container images" },
    ],
  },
  {
    id: "bedrock",
    name: "Bedrock",
    fullName: "Amazon Bedrock",
    category: "ai-ml",
    description: "Fully managed service for building generative AI apps with foundation models.",
    icon: "🪨",
    scope: "region",
    cfnType: "AWS::Bedrock::Agent",
    keywords: ["bedrock", "generative ai", "foundation model", "llm", "genai"],
    configFields: [
      {
        key: "model",
        label: "Foundation Model",
        type: "select",
        default: "anthropic.claude-3-sonnet",
        options: [
          { value: "anthropic.claude-3-sonnet", label: "Claude 3 Sonnet" },
          { value: "anthropic.claude-3-haiku", label: "Claude 3 Haiku" },
          { value: "amazon.titan-text-express", label: "Titan Text Express" },
          { value: "meta.llama3-70b", label: "Llama 3 70B" },
          { value: "cohere.command-r-plus", label: "Cohere Command R+" },
        ],
      },
      { key: "maxTokens", label: "Max Tokens", type: "number", default: 2048 },
      { key: "temperature", label: "Temperature", type: "number", default: 0.7 },
    ],
    commonConnections: [
      { to: "lambda", relationship: "invokes", description: "Agent action groups invoke Lambda" },
      { to: "kendra", relationship: "reads_from", description: "Knowledge base retrieval" },
      {
        to: "s3-bucket",
        relationship: "reads_from",
        description: "Reads knowledge base documents",
      },
      { to: "iam-role", relationship: "assumes", description: "Agent execution role" },
    ],
  },
  {
    id: "rekognition",
    name: "Rekognition",
    fullName: "Amazon Rekognition",
    category: "ai-ml",
    description: "Adds image and video analysis such as object, face, and text detection.",
    icon: "👁️",
    scope: "region",
    cfnType: "AWS::Rekognition::Collection",
    keywords: ["rekognition", "image", "video", "face", "vision", "detection"],
    configFields: [
      {
        key: "feature",
        label: "Feature",
        type: "select",
        default: "DetectLabels",
        options: [
          { value: "DetectLabels", label: "Detect Labels" },
          { value: "DetectFaces", label: "Detect Faces" },
          { value: "DetectText", label: "Detect Text" },
          { value: "DetectModerationLabels", label: "Content Moderation" },
        ],
      },
      { key: "minConfidence", label: "Min Confidence", type: "number", default: 80 },
    ],
    commonConnections: [
      { to: "s3-bucket", relationship: "reads_from", description: "Analyzes images stored in S3" },
      { to: "lambda", relationship: "invokes", description: "Triggers post-processing functions" },
      {
        to: "sns",
        relationship: "publishes_to",
        description: "Video analysis completion notifications",
      },
    ],
  },
  {
    id: "comprehend",
    name: "Comprehend",
    fullName: "Amazon Comprehend",
    category: "ai-ml",
    description: "Natural language processing service for extracting insights from text.",
    icon: "💬",
    scope: "region",
    cfnType: "AWS::Comprehend::DocumentClassifier",
    keywords: ["comprehend", "nlp", "sentiment", "entities", "text", "language"],
    configFields: [
      {
        key: "analysisType",
        label: "Analysis Type",
        type: "select",
        default: "Sentiment",
        options: [
          { value: "Sentiment", label: "Sentiment" },
          { value: "Entities", label: "Entity Recognition" },
          { value: "KeyPhrases", label: "Key Phrases" },
          { value: "PiiEntities", label: "PII Detection" },
        ],
      },
      {
        key: "languageCode",
        label: "Language",
        type: "select",
        default: "en",
        options: [
          { value: "en", label: "English" },
          { value: "es", label: "Spanish" },
          { value: "fr", label: "French" },
          { value: "de", label: "German" },
        ],
      },
    ],
    commonConnections: [
      {
        to: "s3-bucket",
        relationship: "reads_from",
        description: "Reads documents for batch analysis",
      },
      { to: "lambda", relationship: "invokes", description: "Triggers downstream processing" },
      { to: "iam-role", relationship: "assumes", description: "Batch job access role" },
    ],
  },
  {
    id: "textract",
    name: "Textract",
    fullName: "Amazon Textract",
    category: "ai-ml",
    description: "Extracts text, forms, and tables from scanned documents and images.",
    icon: "📄",
    scope: "region",
    cfnType: "AWS::Textract::Adapter",
    keywords: ["textract", "ocr", "document", "forms", "tables", "extraction"],
    configFields: [
      {
        key: "featureType",
        label: "Feature Types",
        type: "multiselect",
        options: [
          { value: "FORMS", label: "Forms" },
          { value: "TABLES", label: "Tables" },
          { value: "SIGNATURES", label: "Signatures" },
          { value: "QUERIES", label: "Queries" },
        ],
      },
      {
        key: "mode",
        label: "Mode",
        type: "select",
        default: "sync",
        options: [
          { value: "sync", label: "Synchronous" },
          { value: "async", label: "Asynchronous" },
        ],
      },
    ],
    commonConnections: [
      { to: "s3-bucket", relationship: "reads_from", description: "Reads documents from S3" },
      {
        to: "sns",
        relationship: "publishes_to",
        description: "Async job completion notifications",
      },
      { to: "lambda", relationship: "invokes", description: "Triggers extraction post-processing" },
    ],
  },
  {
    id: "transcribe",
    name: "Transcribe",
    fullName: "Amazon Transcribe",
    category: "ai-ml",
    description: "Automatic speech recognition service that converts audio to text.",
    icon: "🎙️",
    scope: "region",
    cfnType: "AWS::Transcribe::LanguageModel",
    keywords: ["transcribe", "speech to text", "asr", "audio", "captions"],
    configFields: [
      {
        key: "languageCode",
        label: "Language",
        type: "select",
        default: "en-US",
        options: [
          { value: "en-US", label: "English (US)" },
          { value: "es-US", label: "Spanish (US)" },
          { value: "fr-FR", label: "French" },
          { value: "de-DE", label: "German" },
        ],
      },
      {
        key: "mediaFormat",
        label: "Media Format",
        type: "select",
        default: "mp3",
        options: [
          { value: "mp3", label: "MP3" },
          { value: "mp4", label: "MP4" },
          { value: "wav", label: "WAV" },
          { value: "flac", label: "FLAC" },
        ],
      },
      { key: "showSpeakerLabels", label: "Speaker Diarization", type: "boolean", default: false },
    ],
    commonConnections: [
      {
        to: "s3-bucket",
        relationship: "reads_from",
        description: "Reads audio and writes transcripts",
      },
      { to: "lambda", relationship: "invokes", description: "Triggers transcript post-processing" },
      { to: "comprehend", relationship: "connects_to", description: "Analyze transcribed text" },
    ],
  },
  {
    id: "polly",
    name: "Polly",
    fullName: "Amazon Polly",
    category: "ai-ml",
    description: "Turns text into lifelike speech using deep learning voices.",
    icon: "🗣️",
    scope: "region",
    cfnType: "AWS::Polly::Lexicon",
    keywords: ["polly", "text to speech", "tts", "voice", "speech synthesis"],
    configFields: [
      {
        key: "voiceId",
        label: "Voice",
        type: "select",
        default: "Joanna",
        options: [
          { value: "Joanna", label: "Joanna (en-US)" },
          { value: "Matthew", label: "Matthew (en-US)" },
          { value: "Lupe", label: "Lupe (es-US)" },
          { value: "Amy", label: "Amy (en-GB)" },
        ],
      },
      {
        key: "engine",
        label: "Engine",
        type: "select",
        default: "neural",
        options: [
          { value: "standard", label: "Standard" },
          { value: "neural", label: "Neural" },
          { value: "long-form", label: "Long-form" },
        ],
      },
      {
        key: "outputFormat",
        label: "Output Format",
        type: "select",
        default: "mp3",
        options: [
          { value: "mp3", label: "MP3" },
          { value: "ogg_vorbis", label: "OGG Vorbis" },
          { value: "pcm", label: "PCM" },
        ],
      },
    ],
    commonConnections: [
      {
        to: "s3-bucket",
        relationship: "writes_to",
        description: "Stores synthesized audio output",
      },
      { to: "lambda", relationship: "invokes", description: "Triggers synthesis workflows" },
    ],
  },
  {
    id: "translate",
    name: "Translate",
    fullName: "Amazon Translate",
    category: "ai-ml",
    description: "Neural machine translation service for translating text between languages.",
    icon: "🈯",
    scope: "region",
    cfnType: "AWS::Translate::TerminologyResource",
    keywords: ["translate", "translation", "language", "localization", "nmt"],
    configFields: [
      {
        key: "sourceLanguage",
        label: "Source Language",
        type: "select",
        default: "auto",
        options: [
          { value: "auto", label: "Auto-detect" },
          { value: "en", label: "English" },
          { value: "es", label: "Spanish" },
          { value: "fr", label: "French" },
        ],
      },
      {
        key: "targetLanguage",
        label: "Target Language",
        type: "select",
        default: "es",
        options: [
          { value: "en", label: "English" },
          { value: "es", label: "Spanish" },
          { value: "fr", label: "French" },
          { value: "ja", label: "Japanese" },
        ],
      },
    ],
    commonConnections: [
      {
        to: "s3-bucket",
        relationship: "reads_from",
        description: "Batch translation of documents",
      },
      { to: "lambda", relationship: "invokes", description: "Triggers translation workflows" },
      { to: "comprehend", relationship: "connects_to", description: "Language detection" },
    ],
  },
  {
    id: "lex",
    name: "Lex",
    fullName: "Amazon Lex",
    category: "ai-ml",
    description: "Builds conversational interfaces and chatbots using voice and text.",
    icon: "🤖",
    scope: "region",
    cfnType: "AWS::Lex::Bot",
    keywords: ["lex", "chatbot", "conversational", "bot", "intent", "voice"],
    configFields: [
      {
        key: "localeId",
        label: "Locale",
        type: "select",
        default: "en_US",
        options: [
          { value: "en_US", label: "English (US)" },
          { value: "es_US", label: "Spanish (US)" },
          { value: "fr_FR", label: "French" },
        ],
      },
      {
        key: "confidenceThreshold",
        label: "Intent Confidence Threshold",
        type: "number",
        default: 0.4,
      },
      { key: "childDirected", label: "Child Directed (COPPA)", type: "boolean", default: false },
    ],
    commonConnections: [
      { to: "lambda", relationship: "invokes", description: "Fulfillment via Lambda hooks" },
      { to: "polly", relationship: "connects_to", description: "Voice responses" },
      { to: "cloudwatch-logs", relationship: "writes_to", description: "Logs conversation events" },
    ],
  },
  {
    id: "kendra",
    name: "Kendra",
    fullName: "Amazon Kendra",
    category: "ai-ml",
    description: "Intelligent enterprise search service powered by machine learning.",
    icon: "🔎",
    scope: "region",
    cfnType: "AWS::Kendra::Index",
    keywords: ["kendra", "search", "enterprise search", "rag", "retrieval"],
    configFields: [
      {
        key: "edition",
        label: "Edition",
        type: "select",
        default: "DEVELOPER_EDITION",
        options: [
          { value: "DEVELOPER_EDITION", label: "Developer Edition" },
          { value: "ENTERPRISE_EDITION", label: "Enterprise Edition" },
        ],
      },
      {
        key: "dataSource",
        label: "Data Source",
        type: "select",
        default: "S3",
        options: [
          { value: "S3", label: "Amazon S3" },
          { value: "SHAREPOINT", label: "SharePoint" },
          { value: "DATABASE", label: "Database" },
          { value: "WEBCRAWLER", label: "Web Crawler" },
        ],
      },
    ],
    commonConnections: [
      { to: "s3-bucket", relationship: "reads_from", description: "Indexes documents from S3" },
      { to: "iam-role", relationship: "assumes", description: "Data source access role" },
      { to: "lambda", relationship: "invokes", description: "Custom data source connectors" },
    ],
  },
];

export default aiMl;
