/**
 * Containers service catalog.
 * Every entry is a `ServiceDefinition` and the array is the default export,
 * matching the structure of networking.ts.
 */
import type { ServiceDefinition } from "../types";

const containers: ServiceDefinition[] = [
  {
    id: "ecs-cluster",
    name: "ECS Cluster",
    fullName: "Amazon Elastic Container Service Cluster",
    abbreviation: "ECS",
    category: "containers",
    description: "A logical grouping of tasks or services running on ECS.",
    icon: "📚",
    scope: "region",
    isContainer: true,
    cfnType: "AWS::ECS::Cluster",
    arnPattern: "arn:aws:ecs:{region}:{account}:cluster/{name}",
    keywords: ["ecs", "cluster", "containers", "orchestration", "docker"],
    configFields: [
      {
        key: "clusterName",
        label: "Cluster Name",
        type: "string",
        placeholder: "my-cluster",
        required: true,
      },
      {
        key: "capacityProvider",
        label: "Capacity Provider",
        type: "select",
        default: "FARGATE",
        options: [
          { value: "FARGATE", label: "Fargate" },
          { value: "FARGATE_SPOT", label: "Fargate Spot" },
          { value: "EC2", label: "EC2" },
        ],
      },
      { key: "containerInsights", label: "Container Insights", type: "boolean", default: false },
    ],
    commonConnections: [
      { to: "ecs-service", relationship: "contains", description: "Cluster contains services" },
      {
        to: "fargate",
        relationship: "depends_on",
        description: "Uses Fargate as a capacity provider",
      },
      { to: "cloudwatch", relationship: "monitors", description: "Container Insights metrics" },
    ],
  },
  {
    id: "ecs-service",
    name: "ECS Service",
    fullName: "Amazon Elastic Container Service",
    abbreviation: "ECS",
    category: "containers",
    description: "Maintains a desired count of running task instances in a cluster.",
    icon: "📦",
    scope: "region",
    cfnType: "AWS::ECS::Service",
    arnPattern: "arn:aws:ecs:{region}:{account}:service/{cluster}/{name}",
    keywords: ["ecs", "service", "task", "container", "deployment"],
    configFields: [
      {
        key: "serviceName",
        label: "Service Name",
        type: "string",
        placeholder: "web-service",
        required: true,
      },
      { key: "desiredCount", label: "Desired Count", type: "number", default: 2 },
      {
        key: "launchType",
        label: "Launch Type",
        type: "select",
        default: "FARGATE",
        options: [
          { value: "FARGATE", label: "Fargate" },
          { value: "EC2", label: "EC2" },
          { value: "EXTERNAL", label: "External" },
        ],
      },
      { key: "assignPublicIp", label: "Assign Public IP", type: "boolean", default: false },
    ],
    commonConnections: [
      { to: "ecr", relationship: "reads_from", description: "Pulls images from ECR" },
      {
        to: "target-group",
        relationship: "attached_to",
        description: "Registers tasks behind a load balancer",
      },
      { to: "iam-role", relationship: "assumes", description: "Task execution role" },
      { to: "cloudwatch-logs", relationship: "writes_to", description: "Streams container logs" },
    ],
  },
  {
    id: "eks-cluster",
    name: "EKS Cluster",
    fullName: "Amazon Elastic Kubernetes Service Cluster",
    abbreviation: "EKS",
    category: "containers",
    description: "A managed Kubernetes control plane for running containerized workloads.",
    icon: "☸️",
    scope: "region",
    isContainer: true,
    cfnType: "AWS::EKS::Cluster",
    arnPattern: "arn:aws:eks:{region}:{account}:cluster/{name}",
    keywords: ["eks", "kubernetes", "k8s", "cluster", "containers"],
    configFields: [
      {
        key: "clusterName",
        label: "Cluster Name",
        type: "string",
        placeholder: "prod-eks",
        required: true,
      },
      {
        key: "version",
        label: "Kubernetes Version",
        type: "select",
        default: "1.30",
        options: [
          { value: "1.30", label: "1.30" },
          { value: "1.29", label: "1.29" },
          { value: "1.28", label: "1.28" },
        ],
      },
      {
        key: "endpointAccess",
        label: "Endpoint Access",
        type: "select",
        default: "public",
        options: [
          { value: "public", label: "Public" },
          { value: "private", label: "Private" },
          { value: "public-private", label: "Public and Private" },
        ],
      },
    ],
    commonConnections: [
      { to: "ecr", relationship: "reads_from", description: "Pulls images from ECR" },
      { to: "ec2-instance", relationship: "contains", description: "Runs worker nodes" },
      { to: "iam-role", relationship: "assumes", description: "Cluster service role" },
      {
        to: "cloudwatch-logs",
        relationship: "writes_to",
        description: "Streams control plane logs",
      },
    ],
  },
  {
    id: "ecr",
    name: "ECR",
    fullName: "Amazon Elastic Container Registry",
    abbreviation: "ECR",
    category: "containers",
    description: "A fully managed registry for storing and pulling Docker container images.",
    icon: "🐳",
    scope: "region",
    cfnType: "AWS::ECR::Repository",
    arnPattern: "arn:aws:ecr:{region}:{account}:repository/{name}",
    keywords: ["ecr", "registry", "docker", "images", "repository"],
    configFields: [
      {
        key: "repositoryName",
        label: "Repository Name",
        type: "string",
        placeholder: "my-app",
        required: true,
      },
      {
        key: "imageTagMutability",
        label: "Tag Mutability",
        type: "select",
        default: "MUTABLE",
        options: [
          { value: "MUTABLE", label: "Mutable" },
          { value: "IMMUTABLE", label: "Immutable" },
        ],
      },
      { key: "scanOnPush", label: "Scan On Push", type: "boolean", default: true },
    ],
    commonConnections: [
      { to: "kms", relationship: "depends_on", description: "Encrypts images at rest" },
      {
        to: "iam-policy",
        relationship: "depends_on",
        description: "Repository policy controls pull/push access",
      },
    ],
  },
  {
    id: "fargate",
    name: "Fargate",
    fullName: "AWS Fargate",
    category: "containers",
    description: "Serverless compute engine that runs containers without managing servers.",
    icon: "☁️",
    scope: "region",
    cfnType: "AWS::ECS::TaskDefinition",
    arnPattern: "arn:aws:ecs:{region}:{account}:task-definition/{family}:{revision}",
    keywords: ["fargate", "serverless", "containers", "task", "compute"],
    configFields: [
      {
        key: "cpu",
        label: "Task CPU",
        type: "select",
        default: "512",
        options: [
          { value: "256", label: "0.25 vCPU" },
          { value: "512", label: "0.5 vCPU" },
          { value: "1024", label: "1 vCPU" },
          { value: "2048", label: "2 vCPU" },
          { value: "4096", label: "4 vCPU" },
        ],
      },
      {
        key: "memory",
        label: "Task Memory",
        type: "select",
        default: "1024",
        options: [
          { value: "512", label: "512 MB" },
          { value: "1024", label: "1 GB" },
          { value: "2048", label: "2 GB" },
          { value: "4096", label: "4 GB" },
        ],
      },
      {
        key: "platformVersion",
        label: "Platform Version",
        type: "string",
        placeholder: "LATEST",
        default: "LATEST",
      },
    ],
    commonConnections: [
      { to: "ecs-service", relationship: "depends_on", description: "Provides compute for tasks" },
      { to: "ecr", relationship: "reads_from", description: "Pulls task container images" },
      { to: "iam-role", relationship: "assumes", description: "Task execution role" },
    ],
  },
  {
    id: "app-runner",
    name: "App Runner",
    fullName: "AWS App Runner",
    category: "containers",
    description:
      "Fully managed service to deploy containerized web apps and APIs from source or image.",
    icon: "🏃",
    scope: "region",
    cfnType: "AWS::AppRunner::Service",
    arnPattern: "arn:aws:apprunner:{region}:{account}:service/{name}/{id}",
    keywords: ["app runner", "containers", "web app", "api", "managed"],
    configFields: [
      {
        key: "serviceName",
        label: "Service Name",
        type: "string",
        placeholder: "my-web-app",
        required: true,
      },
      {
        key: "sourceType",
        label: "Source Type",
        type: "select",
        default: "image",
        options: [
          { value: "image", label: "Container Image" },
          { value: "repository", label: "Source Repository" },
        ],
      },
      {
        key: "cpu",
        label: "vCPU",
        type: "select",
        default: "1",
        options: [
          { value: "0.25", label: "0.25 vCPU" },
          { value: "0.5", label: "0.5 vCPU" },
          { value: "1", label: "1 vCPU" },
          { value: "2", label: "2 vCPU" },
        ],
      },
      { key: "autoScaling", label: "Auto Scaling", type: "boolean", default: true },
    ],
    commonConnections: [
      { to: "ecr", relationship: "reads_from", description: "Pulls container images" },
      { to: "iam-role", relationship: "assumes", description: "Service instance role" },
      { to: "cloudwatch-logs", relationship: "writes_to", description: "Streams application logs" },
    ],
  },
];

export default containers;
