/**
 * Application Integration service catalog.
 * Every entry is a `ServiceDefinition` and the array is the default export,
 * following the canonical style of networking.ts.
 */
import type { ServiceDefinition } from "../types";

const integration: ServiceDefinition[] = [
  {
    id: "sqs",
    name: "SQS",
    fullName: "Amazon Simple Queue Service",
    abbreviation: "SQS",
    category: "integration",
    description: "Fully managed message queuing service for decoupling components.",
    icon: "📨",
    scope: "region",
    cfnType: "AWS::SQS::Queue",
    arnPattern: "arn:aws:sqs:{region}:{account}:{name}",
    keywords: ["queue", "messaging", "sqs", "fifo", "decoupling"],
    configFields: [
      {
        key: "queueType",
        label: "Queue Type",
        type: "select",
        default: "standard",
        options: [
          { value: "standard", label: "Standard" },
          { value: "fifo", label: "FIFO" },
        ],
      },
      { key: "visibilityTimeout", label: "Visibility Timeout (s)", type: "number", default: 30 },
      { key: "retentionPeriod", label: "Message Retention (s)", type: "number", default: 345600 },
      { key: "encryption", label: "SSE Encryption", type: "boolean", default: true },
    ],
    commonConnections: [
      { to: "lambda", relationship: "invokes", description: "Queue triggers Lambda consumer" },
      { to: "sqs", relationship: "writes_to", description: "Dead-letter queue" },
    ],
  },
  {
    id: "sns",
    name: "SNS",
    fullName: "Amazon Simple Notification Service",
    abbreviation: "SNS",
    category: "integration",
    description: "Managed pub/sub messaging for fan-out to multiple subscribers.",
    icon: "📣",
    scope: "region",
    cfnType: "AWS::SNS::Topic",
    arnPattern: "arn:aws:sns:{region}:{account}:{name}",
    keywords: ["sns", "pubsub", "notification", "topic", "fanout"],
    configFields: [
      {
        key: "topicType",
        label: "Topic Type",
        type: "select",
        default: "standard",
        options: [
          { value: "standard", label: "Standard" },
          { value: "fifo", label: "FIFO" },
        ],
      },
      { key: "displayName", label: "Display Name", type: "string", placeholder: "order-events" },
      { key: "encryption", label: "SSE Encryption", type: "boolean", default: true },
    ],
    commonConnections: [
      { to: "sqs", relationship: "publishes_to", description: "Fan-out to queues" },
      { to: "lambda", relationship: "invokes", description: "Topic invokes Lambda" },
    ],
  },
  {
    id: "eventbridge",
    name: "EventBridge",
    fullName: "Amazon EventBridge",
    category: "integration",
    description: "Serverless event bus that routes events between AWS and SaaS sources.",
    icon: "🔀",
    scope: "region",
    cfnType: "AWS::Events::Rule",
    arnPattern: "arn:aws:events:{region}:{account}:rule/{name}",
    keywords: ["eventbridge", "event bus", "events", "rule", "schedule"],
    configFields: [
      {
        key: "busName",
        label: "Event Bus",
        type: "string",
        default: "default",
        placeholder: "default",
      },
      {
        key: "eventPattern",
        label: "Event Pattern",
        type: "text",
        placeholder: '{ "source": ["my.app"] }',
      },
      {
        key: "scheduleExpression",
        label: "Schedule Expression",
        type: "string",
        placeholder: "rate(5 minutes)",
      },
    ],
    commonConnections: [
      { to: "lambda", relationship: "invokes", description: "Rule target invokes Lambda" },
      { to: "step-functions", relationship: "invokes", description: "Rule starts state machine" },
      { to: "sqs", relationship: "publishes_to", description: "Route events to a queue" },
    ],
  },
  {
    id: "kinesis-data-streams",
    name: "Kinesis Streams",
    fullName: "Amazon Kinesis Data Streams",
    category: "integration",
    description: "Real-time streaming data ingestion and processing at scale.",
    icon: "🌊",
    scope: "region",
    cfnType: "AWS::Kinesis::Stream",
    arnPattern: "arn:aws:kinesis:{region}:{account}:stream/{name}",
    keywords: ["kinesis", "stream", "streaming", "real-time", "shard"],
    configFields: [
      {
        key: "mode",
        label: "Capacity Mode",
        type: "select",
        default: "on-demand",
        options: [
          { value: "on-demand", label: "On-Demand" },
          { value: "provisioned", label: "Provisioned" },
        ],
      },
      { key: "shardCount", label: "Shard Count", type: "number", default: 1 },
      { key: "retentionPeriod", label: "Retention (hours)", type: "number", default: 24 },
    ],
    commonConnections: [
      { to: "lambda", relationship: "invokes", description: "Stream triggers Lambda processor" },
      {
        to: "kinesis-firehose",
        relationship: "writes_to",
        description: "Deliver records to Firehose",
      },
    ],
  },
  {
    id: "step-functions",
    name: "Step Functions",
    fullName: "AWS Step Functions",
    abbreviation: "SFN",
    category: "integration",
    description: "Serverless orchestration that coordinates workflows as state machines.",
    icon: "🪜",
    scope: "region",
    cfnType: "AWS::StepFunctions::StateMachine",
    arnPattern: "arn:aws:states:{region}:{account}:stateMachine:{name}",
    keywords: ["step functions", "workflow", "orchestration", "state machine"],
    configFields: [
      {
        key: "stateMachineType",
        label: "Type",
        type: "select",
        default: "STANDARD",
        options: [
          { value: "STANDARD", label: "Standard" },
          { value: "EXPRESS", label: "Express" },
        ],
      },
      {
        key: "loggingLevel",
        label: "Logging Level",
        type: "select",
        default: "ERROR",
        options: [
          { value: "OFF", label: "Off" },
          { value: "ERROR", label: "Error" },
          { value: "ALL", label: "All" },
        ],
      },
    ],
    commonConnections: [
      { to: "lambda", relationship: "invokes", description: "Task state invokes Lambda" },
      { to: "sns", relationship: "publishes_to", description: "Notify on completion" },
      { to: "dynamodb", relationship: "writes_to", description: "Persist workflow state" },
    ],
  },
  {
    id: "api-gateway",
    name: "API Gateway",
    fullName: "Amazon API Gateway",
    category: "integration",
    description: "Managed service for creating, publishing, and securing REST/HTTP/WebSocket APIs.",
    icon: "🚪",
    scope: "region",
    cfnType: "AWS::ApiGateway::RestApi",
    arnPattern: "arn:aws:apigateway:{region}::/restapis/{id}",
    keywords: ["api gateway", "rest", "http api", "endpoint", "websocket"],
    configFields: [
      {
        key: "apiType",
        label: "API Type",
        type: "select",
        default: "REST",
        options: [
          { value: "REST", label: "REST" },
          { value: "HTTP", label: "HTTP" },
          { value: "WEBSOCKET", label: "WebSocket" },
        ],
      },
      {
        key: "endpointType",
        label: "Endpoint Type",
        type: "select",
        default: "REGIONAL",
        options: [
          { value: "REGIONAL", label: "Regional" },
          { value: "EDGE", label: "Edge-optimized" },
          { value: "PRIVATE", label: "Private" },
        ],
      },
      {
        key: "stageName",
        label: "Stage Name",
        type: "string",
        default: "prod",
        placeholder: "prod",
      },
    ],
    commonConnections: [
      { to: "lambda", relationship: "invokes", description: "Proxy integration to Lambda" },
      { to: "cognito", relationship: "depends_on", description: "Cognito authorizer" },
      { to: "step-functions", relationship: "invokes", description: "Direct service integration" },
    ],
  },
  {
    id: "amazon-mq",
    name: "Amazon MQ",
    fullName: "Amazon MQ",
    category: "integration",
    description: "Managed message broker for ActiveMQ and RabbitMQ workloads.",
    icon: "🐰",
    scope: "vpc",
    cfnType: "AWS::AmazonMQ::Broker",
    arnPattern: "arn:aws:mq:{region}:{account}:broker:{name}",
    keywords: ["amazon mq", "activemq", "rabbitmq", "broker", "jms"],
    configFields: [
      {
        key: "engineType",
        label: "Broker Engine",
        type: "select",
        default: "RABBITMQ",
        options: [
          { value: "ACTIVEMQ", label: "ActiveMQ" },
          { value: "RABBITMQ", label: "RabbitMQ" },
        ],
      },
      {
        key: "deploymentMode",
        label: "Deployment Mode",
        type: "select",
        default: "SINGLE_INSTANCE",
        options: [
          { value: "SINGLE_INSTANCE", label: "Single Instance" },
          { value: "ACTIVE_STANDBY_MULTI_AZ", label: "Active/Standby Multi-AZ" },
          { value: "CLUSTER_MULTI_AZ", label: "Cluster Multi-AZ" },
        ],
      },
      {
        key: "hostInstanceType",
        label: "Instance Type",
        type: "select",
        default: "mq.m5.large",
        options: [
          { value: "mq.t3.micro", label: "mq.t3.micro" },
          { value: "mq.m5.large", label: "mq.m5.large" },
          { value: "mq.m5.xlarge", label: "mq.m5.xlarge" },
        ],
      },
    ],
    commonConnections: [
      {
        to: "ec2-instance",
        relationship: "connects_to",
        description: "Producers/consumers connect to broker",
      },
      { to: "lambda", relationship: "invokes", description: "Event source mapping to Lambda" },
    ],
  },
  {
    id: "appsync",
    name: "AppSync",
    fullName: "AWS AppSync",
    category: "integration",
    description: "Managed GraphQL service connecting apps to data sources in real time.",
    icon: "🔺",
    scope: "region",
    cfnType: "AWS::AppSync::GraphQLApi",
    arnPattern: "arn:aws:appsync:{region}:{account}:apis/{id}",
    keywords: ["appsync", "graphql", "api", "subscriptions", "resolver"],
    configFields: [
      {
        key: "authType",
        label: "Default Auth",
        type: "select",
        default: "API_KEY",
        options: [
          { value: "API_KEY", label: "API Key" },
          { value: "AMAZON_COGNITO_USER_POOLS", label: "Cognito User Pools" },
          { value: "AWS_IAM", label: "IAM" },
          { value: "OPENID_CONNECT", label: "OpenID Connect" },
        ],
      },
      { key: "xrayEnabled", label: "X-Ray Tracing", type: "boolean", default: false },
    ],
    commonConnections: [
      { to: "dynamodb", relationship: "reads_from", description: "DynamoDB data source" },
      { to: "lambda", relationship: "invokes", description: "Lambda resolver" },
      { to: "cognito", relationship: "depends_on", description: "User pool authorization" },
    ],
  },
];

export default integration;
