/**
 * Networking & Content Delivery service catalog.
 * This file is the canonical example for all other category catalogs:
 * every entry is a `ServiceDefinition` and the array is the default export.
 */
import type { ServiceDefinition } from "../types";

const networking: ServiceDefinition[] = [
  {
    id: "vpc",
    name: "VPC",
    fullName: "Amazon Virtual Private Cloud",
    abbreviation: "VPC",
    category: "networking",
    description: "An isolated virtual network in which you launch AWS resources.",
    icon: "🏛️",
    scope: "region",
    isContainer: true,
    cfnType: "AWS::EC2::VPC",
    arnPattern: "arn:aws:ec2:{region}:{account}:vpc/{id}",
    keywords: ["network", "vpc", "isolation", "cidr"],
    configFields: [
      {
        key: "cidr",
        label: "CIDR Block",
        type: "cidr",
        placeholder: "10.0.0.0/16",
        default: "10.0.0.0/16",
        required: true,
      },
      { key: "enableDnsHostnames", label: "DNS Hostnames", type: "boolean", default: true },
      {
        key: "tenancy",
        label: "Tenancy",
        type: "select",
        default: "default",
        options: [
          { value: "default", label: "Default" },
          { value: "dedicated", label: "Dedicated" },
        ],
      },
      { key: "enableFlowLogs", label: "VPC Flow Logs", type: "boolean", default: false },
    ],
    commonConnections: [
      { to: "subnet-public", relationship: "contains", description: "VPC contains subnets" },
      { to: "subnet-private", relationship: "contains" },
      { to: "internet-gateway", relationship: "attached_to" },
    ],
  },
  {
    id: "subnet-public",
    name: "Public Subnet",
    fullName: "Amazon VPC Subnet (Public)",
    category: "networking",
    description: "A subnet with a route to an Internet Gateway for public access.",
    icon: "🟩",
    scope: "az",
    isContainer: true,
    cfnType: "AWS::EC2::Subnet",
    keywords: ["subnet", "public", "network", "az"],
    configFields: [
      {
        key: "cidr",
        label: "CIDR Block",
        type: "cidr",
        placeholder: "10.0.1.0/24",
        default: "10.0.1.0/24",
        required: true,
      },
      { key: "az", label: "Availability Zone", type: "string", placeholder: "us-east-1a" },
      { key: "mapPublicIp", label: "Auto-assign Public IP", type: "boolean", default: true },
    ],
    commonConnections: [
      { to: "route-table", relationship: "attached_to" },
      { to: "nat-gateway", relationship: "contains" },
    ],
  },
  {
    id: "subnet-private",
    name: "Private Subnet",
    fullName: "Amazon VPC Subnet (Private)",
    category: "networking",
    description: "A subnet without a direct route to the internet.",
    icon: "🟥",
    scope: "az",
    isContainer: true,
    cfnType: "AWS::EC2::Subnet",
    keywords: ["subnet", "private", "network", "az"],
    configFields: [
      {
        key: "cidr",
        label: "CIDR Block",
        type: "cidr",
        placeholder: "10.0.2.0/24",
        default: "10.0.2.0/24",
        required: true,
      },
      { key: "az", label: "Availability Zone", type: "string", placeholder: "us-east-1a" },
      { key: "mapPublicIp", label: "Auto-assign Public IP", type: "boolean", default: false },
    ],
    commonConnections: [{ to: "route-table", relationship: "attached_to" }],
  },
  {
    id: "route-table",
    name: "Route Table",
    fullName: "Amazon VPC Route Table",
    category: "networking",
    description: "Controls routing of network traffic for associated subnets.",
    icon: "🧭",
    scope: "vpc",
    cfnType: "AWS::EC2::RouteTable",
    keywords: ["route", "routing", "network"],
    configFields: [
      { key: "routes", label: "Routes", type: "text", placeholder: "0.0.0.0/0 -> igw-..." },
    ],
    commonConnections: [
      { to: "internet-gateway", relationship: "routes_to" },
      { to: "nat-gateway", relationship: "routes_to" },
    ],
  },
  {
    id: "nacl",
    name: "Network ACL",
    fullName: "Amazon VPC Network ACL",
    abbreviation: "NACL",
    category: "networking",
    description: "Stateless subnet-level firewall with ordered allow/deny rules.",
    icon: "🚧",
    scope: "vpc",
    cfnType: "AWS::EC2::NetworkAcl",
    keywords: ["nacl", "firewall", "acl", "stateless"],
    configFields: [
      { key: "rules", label: "Rules", type: "text", placeholder: "100 allow tcp 0-65535" },
    ],
    commonConnections: [
      { to: "subnet-public", relationship: "attached_to" },
      { to: "subnet-private", relationship: "attached_to" },
    ],
  },
  {
    id: "internet-gateway",
    name: "Internet Gateway",
    fullName: "Amazon VPC Internet Gateway",
    abbreviation: "IGW",
    category: "networking",
    description: "Enables internet access for resources in public subnets.",
    icon: "🌍",
    scope: "vpc",
    cfnType: "AWS::EC2::InternetGateway",
    keywords: ["igw", "internet", "gateway"],
    configFields: [],
    commonConnections: [{ to: "vpc", relationship: "attached_to" }],
  },
  {
    id: "nat-gateway",
    name: "NAT Gateway",
    fullName: "Amazon VPC NAT Gateway",
    abbreviation: "NAT GW",
    category: "networking",
    description: "Allows private subnet resources outbound internet access.",
    icon: "↗️",
    scope: "subnet",
    cfnType: "AWS::EC2::NatGateway",
    keywords: ["nat", "gateway", "egress"],
    configFields: [
      {
        key: "connectivityType",
        label: "Connectivity",
        type: "select",
        default: "public",
        options: [
          { value: "public", label: "Public" },
          { value: "private", label: "Private" },
        ],
      },
    ],
    commonConnections: [{ to: "subnet-public", relationship: "attached_to" }],
  },
  {
    id: "security-group",
    name: "Security Group",
    fullName: "Amazon VPC Security Group",
    abbreviation: "SG",
    category: "networking",
    description: "Stateful virtual firewall controlling traffic to resources.",
    icon: "🧱",
    scope: "vpc",
    cfnType: "AWS::EC2::SecurityGroup",
    keywords: ["security group", "sg", "firewall", "stateful"],
    configFields: [
      { key: "ingress", label: "Ingress Rules", type: "text", placeholder: "tcp 443 0.0.0.0/0" },
      { key: "egress", label: "Egress Rules", type: "text", placeholder: "all 0.0.0.0/0" },
    ],
    commonConnections: [{ to: "security-group", relationship: "allows" }],
  },
  {
    id: "elastic-load-balancer",
    name: "ALB / ELB",
    fullName: "Elastic Load Balancing",
    abbreviation: "ELB",
    category: "networking",
    description: "Distributes incoming traffic across multiple targets.",
    icon: "⚖️",
    scope: "vpc",
    cfnType: "AWS::ElasticLoadBalancingV2::LoadBalancer",
    keywords: ["alb", "elb", "nlb", "load balancer"],
    configFields: [
      {
        key: "lbType",
        label: "Type",
        type: "select",
        default: "application",
        options: [
          { value: "application", label: "Application (ALB)" },
          { value: "network", label: "Network (NLB)" },
          { value: "gateway", label: "Gateway (GWLB)" },
        ],
      },
      {
        key: "scheme",
        label: "Scheme",
        type: "select",
        default: "internet-facing",
        options: [
          { value: "internet-facing", label: "Internet-facing" },
          { value: "internal", label: "Internal" },
        ],
      },
      {
        key: "listenerProtocol",
        label: "Listener Protocol",
        type: "select",
        default: "HTTPS",
        options: [
          { value: "HTTP", label: "HTTP" },
          { value: "HTTPS", label: "HTTPS" },
          { value: "TCP", label: "TCP" },
          { value: "TLS", label: "TLS" },
        ],
      },
      {
        key: "sslPolicy",
        label: "TLS Security Policy",
        type: "string",
        placeholder: "ELBSecurityPolicy-TLS13-1-2-2021-06",
      },
    ],
    commonConnections: [{ to: "target-group", relationship: "targets" }],
  },
  {
    id: "target-group",
    name: "Target Group",
    fullName: "Elastic Load Balancing Target Group",
    abbreviation: "TG",
    category: "networking",
    description: "A group of targets (instances, IPs, Lambdas) for a load balancer.",
    icon: "🎯",
    scope: "vpc",
    cfnType: "AWS::ElasticLoadBalancingV2::TargetGroup",
    keywords: ["target group", "targets"],
    configFields: [
      { key: "port", label: "Port", type: "number", default: 80 },
      {
        key: "protocol",
        label: "Protocol",
        type: "select",
        default: "HTTP",
        options: [
          { value: "HTTP", label: "HTTP" },
          { value: "HTTPS", label: "HTTPS" },
          { value: "TCP", label: "TCP" },
        ],
      },
      {
        key: "healthCheckPath",
        label: "Health Check Path",
        type: "string",
        placeholder: "/health",
      },
    ],
    commonConnections: [
      { to: "ec2-instance", relationship: "targets" },
      { to: "ecs-service", relationship: "targets" },
    ],
  },
  {
    id: "route53",
    name: "Route 53",
    fullName: "Amazon Route 53",
    category: "networking",
    description: "Scalable DNS and domain name registration service.",
    icon: "🧬",
    scope: "global",
    cfnType: "AWS::Route53::HostedZone",
    keywords: ["dns", "route53", "domain", "hosted zone"],
    configFields: [
      { key: "domain", label: "Domain", type: "string", placeholder: "example.com" },
      {
        key: "recordType",
        label: "Record Type",
        type: "select",
        default: "A",
        options: [
          { value: "A", label: "A" },
          { value: "AAAA", label: "AAAA" },
          { value: "CNAME", label: "CNAME" },
          { value: "ALIAS", label: "ALIAS" },
        ],
      },
    ],
    commonConnections: [
      { to: "elastic-load-balancer", relationship: "routes_to" },
      { to: "cloudfront", relationship: "routes_to" },
    ],
  },
  {
    id: "route53-record",
    name: "Route 53 Record",
    fullName: "Amazon Route 53 Record Set",
    category: "networking",
    description: "A DNS record set within a Route 53 hosted zone.",
    icon: "📇",
    scope: "global",
    cfnType: "AWS::Route53::RecordSet",
    keywords: ["dns", "record", "recordset", "route53", "alias"],
    configFields: [
      { key: "name", label: "Record Name", type: "string", placeholder: "www.example.com" },
      {
        key: "type",
        label: "Record Type",
        type: "select",
        default: "A",
        options: [
          { value: "A", label: "A" },
          { value: "AAAA", label: "AAAA" },
          { value: "CNAME", label: "CNAME" },
          { value: "TXT", label: "TXT" },
          { value: "MX", label: "MX" },
          { value: "NS", label: "NS" },
          { value: "ALIAS", label: "ALIAS" },
        ],
      },
      { key: "ttl", label: "TTL (seconds)", type: "number", default: 300 },
    ],
    commonConnections: [
      { to: "route53", relationship: "attached_to" },
      { to: "elastic-load-balancer", relationship: "routes_to" },
    ],
  },
  {
    id: "vpc-peering",
    name: "VPC Peering",
    fullName: "Amazon VPC Peering Connection",
    category: "networking",
    description: "Private network connection between two VPCs.",
    icon: "🔗",
    scope: "region",
    cfnType: "AWS::EC2::VPCPeeringConnection",
    keywords: ["peering", "vpc", "cross-vpc"],
    configFields: [],
    commonConnections: [{ to: "vpc", relationship: "peers_with" }],
  },
  {
    id: "transit-gateway",
    name: "Transit Gateway",
    fullName: "AWS Transit Gateway",
    abbreviation: "TGW",
    category: "networking",
    description: "Central hub connecting VPCs and on-premises networks.",
    icon: "🛰️",
    scope: "region",
    cfnType: "AWS::EC2::TransitGateway",
    keywords: ["transit gateway", "tgw", "hub"],
    configFields: [],
    commonConnections: [{ to: "vpc", relationship: "connects_to" }],
  },
  {
    id: "vpc-endpoint",
    name: "VPC Endpoint",
    fullName: "Amazon VPC Endpoint (PrivateLink)",
    category: "networking",
    description: "Private connectivity to AWS services without internet egress.",
    icon: "🔌",
    scope: "vpc",
    cfnType: "AWS::EC2::VPCEndpoint",
    keywords: ["endpoint", "privatelink", "vpc"],
    configFields: [
      {
        key: "endpointType",
        label: "Type",
        type: "select",
        default: "Interface",
        options: [
          { value: "Interface", label: "Interface" },
          { value: "Gateway", label: "Gateway" },
        ],
      },
      {
        key: "service",
        label: "Service Name",
        type: "string",
        placeholder: "com.amazonaws.us-east-1.s3",
      },
    ],
    commonConnections: [{ to: "s3-bucket", relationship: "connects_to" }],
  },
];

export default networking;
