/**
 * Storage service catalog.
 * Every entry is a `ServiceDefinition` and the array is the default export,
 * mirroring the structure of networking.ts.
 */
import type { ServiceDefinition } from "../types";

const storage: ServiceDefinition[] = [
  {
    id: "s3-bucket",
    name: "S3",
    fullName: "Amazon Simple Storage Service",
    abbreviation: "S3",
    category: "storage",
    description: "Object storage offering virtually unlimited scalability and durability.",
    icon: "🪣",
    scope: "region",
    cfnType: "AWS::S3::Bucket",
    arnPattern: "arn:aws:s3:::{bucket}",
    keywords: ["s3", "object", "bucket", "storage", "blob"],
    configFields: [
      {
        key: "bucketName",
        label: "Bucket Name",
        type: "string",
        placeholder: "my-app-bucket",
        required: true,
      },
      { key: "versioning", label: "Versioning", type: "boolean", default: false },
      { key: "blockPublicAccess", label: "Block Public Access", type: "boolean", default: true },
      {
        key: "storageClass",
        label: "Default Storage Class",
        type: "select",
        default: "STANDARD",
        options: [
          { value: "STANDARD", label: "Standard" },
          { value: "INTELLIGENT_TIERING", label: "Intelligent-Tiering" },
          { value: "STANDARD_IA", label: "Standard-IA" },
          { value: "ONEZONE_IA", label: "One Zone-IA" },
        ],
      },
      {
        key: "encryption",
        label: "Encryption",
        type: "select",
        default: "SSE-S3",
        options: [
          { value: "SSE-S3", label: "SSE-S3" },
          { value: "SSE-KMS", label: "SSE-KMS" },
          { value: "DSSE-KMS", label: "DSSE-KMS" },
        ],
      },
      {
        key: "kmsKeyId",
        label: "KMS Key (ARN/ID)",
        type: "string",
        placeholder: "arn:aws:kms:…:key/…",
        help: "Customer-managed key for SSE-KMS / DSSE-KMS. Blank uses the AWS-managed key.",
      },
      {
        key: "objectOwnership",
        label: "Object Ownership",
        type: "select",
        default: "BucketOwnerEnforced",
        help: "BucketOwnerEnforced disables ACLs (recommended).",
        options: [
          { value: "BucketOwnerEnforced", label: "Bucket owner enforced (ACLs disabled)" },
          { value: "BucketOwnerPreferred", label: "Bucket owner preferred" },
          { value: "ObjectWriter", label: "Object writer" },
        ],
      },
    ],
    commonConnections: [
      { to: "kms", relationship: "depends_on", description: "Encrypts objects with a KMS key" },
      { to: "cloudfront", relationship: "connects_to", description: "Serves content as an origin" },
      {
        to: "lambda",
        relationship: "invokes",
        description: "Triggers a function on object events",
      },
      {
        to: "s3-glacier",
        relationship: "writes_to",
        description: "Lifecycle transition to archive",
      },
    ],
  },
  {
    id: "ebs-volume",
    name: "EBS",
    fullName: "Amazon Elastic Block Store",
    abbreviation: "EBS",
    category: "storage",
    description: "Persistent block-storage volumes attached to EC2 instances.",
    icon: "💽",
    scope: "az",
    cfnType: "AWS::EC2::Volume",
    arnPattern: "arn:aws:ec2:{region}:{account}:volume/{id}",
    keywords: ["ebs", "block", "volume", "disk", "ec2"],
    configFields: [
      {
        key: "volumeType",
        label: "Volume Type",
        type: "select",
        default: "gp3",
        options: [
          { value: "gp3", label: "General Purpose SSD (gp3)" },
          { value: "gp2", label: "General Purpose SSD (gp2)" },
          { value: "io2", label: "Provisioned IOPS SSD (io2)" },
          { value: "st1", label: "Throughput Optimized HDD (st1)" },
          { value: "sc1", label: "Cold HDD (sc1)" },
        ],
      },
      { key: "sizeGiB", label: "Size (GiB)", type: "number", default: 100, required: true },
      { key: "iops", label: "IOPS", type: "number", placeholder: "3000" },
      { key: "encrypted", label: "Encrypted", type: "boolean", default: true },
    ],
    commonConnections: [
      {
        to: "ec2-instance",
        relationship: "attached_to",
        description: "Mounted to an EC2 instance",
      },
      { to: "kms", relationship: "depends_on", description: "Volume encryption key" },
      { to: "aws-backup", relationship: "depends_on", description: "Protected by backup plans" },
    ],
  },
  {
    id: "efs",
    name: "EFS",
    fullName: "Amazon Elastic File System",
    abbreviation: "EFS",
    category: "storage",
    description: "Fully managed, elastic NFS file system shared across many instances.",
    icon: "🗄️",
    scope: "vpc",
    cfnType: "AWS::EFS::FileSystem",
    arnPattern: "arn:aws:elasticfilesystem:{region}:{account}:file-system/{id}",
    keywords: ["efs", "nfs", "file system", "shared", "elastic"],
    configFields: [
      {
        key: "performanceMode",
        label: "Performance Mode",
        type: "select",
        default: "generalPurpose",
        options: [
          { value: "generalPurpose", label: "General Purpose" },
          { value: "maxIO", label: "Max I/O" },
        ],
      },
      {
        key: "throughputMode",
        label: "Throughput Mode",
        type: "select",
        default: "elastic",
        options: [
          { value: "elastic", label: "Elastic" },
          { value: "bursting", label: "Bursting" },
          { value: "provisioned", label: "Provisioned" },
        ],
      },
      { key: "encrypted", label: "Encryption at Rest", type: "boolean", default: true },
    ],
    commonConnections: [
      { to: "ec2-instance", relationship: "attached_to", description: "Mounted by EC2 instances" },
      {
        to: "ecs-service",
        relationship: "attached_to",
        description: "Persistent volume for containers",
      },
      {
        to: "lambda",
        relationship: "connects_to",
        description: "File system access for functions",
      },
      { to: "kms", relationship: "depends_on", description: "Encryption key" },
    ],
  },
  {
    id: "fsx",
    name: "FSx",
    fullName: "Amazon FSx",
    abbreviation: "FSx",
    category: "storage",
    description: "Fully managed third-party file systems such as Windows, Lustre and NetApp ONTAP.",
    icon: "📁",
    scope: "vpc",
    cfnType: "AWS::FSx::FileSystem",
    arnPattern: "arn:aws:fsx:{region}:{account}:file-system/{id}",
    keywords: ["fsx", "lustre", "windows", "ontap", "file system"],
    configFields: [
      {
        key: "fileSystemType",
        label: "File System Type",
        type: "select",
        default: "WINDOWS",
        options: [
          { value: "WINDOWS", label: "Windows File Server" },
          { value: "LUSTRE", label: "Lustre" },
          { value: "ONTAP", label: "NetApp ONTAP" },
          { value: "OPENZFS", label: "OpenZFS" },
        ],
      },
      {
        key: "storageCapacityGiB",
        label: "Storage Capacity (GiB)",
        type: "number",
        default: 1024,
        required: true,
      },
      {
        key: "deploymentType",
        label: "Deployment Type",
        type: "select",
        default: "MULTI_AZ",
        options: [
          { value: "MULTI_AZ", label: "Multi-AZ" },
          { value: "SINGLE_AZ", label: "Single-AZ" },
        ],
      },
    ],
    commonConnections: [
      { to: "ec2-instance", relationship: "attached_to", description: "Mounted by EC2 instances" },
      { to: "s3-bucket", relationship: "connects_to", description: "Lustre data repository link" },
      { to: "kms", relationship: "depends_on", description: "Encryption key" },
    ],
  },
  {
    id: "storage-gateway",
    name: "Storage Gateway",
    fullName: "AWS Storage Gateway",
    category: "storage",
    description: "Hybrid storage connecting on-premises applications to AWS cloud storage.",
    icon: "🌉",
    scope: "region",
    cfnType: "AWS::StorageGateway::Gateway",
    keywords: ["storage gateway", "hybrid", "on-premises", "file", "volume", "tape"],
    configFields: [
      {
        key: "gatewayType",
        label: "Gateway Type",
        type: "select",
        default: "FILE_S3",
        options: [
          { value: "FILE_S3", label: "Amazon S3 File Gateway" },
          { value: "FILE_FSX_SMB", label: "Amazon FSx File Gateway" },
          { value: "CACHED", label: "Volume Gateway (Cached)" },
          { value: "STORED", label: "Volume Gateway (Stored)" },
          { value: "VTL", label: "Tape Gateway" },
        ],
      },
      {
        key: "gatewayName",
        label: "Gateway Name",
        type: "string",
        placeholder: "on-prem-gw",
        required: true,
      },
    ],
    commonConnections: [
      { to: "s3-bucket", relationship: "writes_to", description: "Backs file/volume shares to S3" },
      { to: "fsx", relationship: "connects_to", description: "Caches FSx file shares on-premises" },
      {
        to: "aws-backup",
        relationship: "depends_on",
        description: "Tape archives managed by Backup",
      },
    ],
  },
  {
    id: "aws-backup",
    name: "Backup",
    fullName: "AWS Backup",
    category: "storage",
    description: "Centralized, policy-based backup across AWS services and on-premises.",
    icon: "🛟",
    scope: "region",
    cfnType: "AWS::Backup::BackupPlan",
    arnPattern: "arn:aws:backup:{region}:{account}:backup-plan:{id}",
    keywords: ["backup", "restore", "recovery", "vault", "snapshot"],
    configFields: [
      {
        key: "scheduleExpression",
        label: "Schedule",
        type: "string",
        placeholder: "cron(0 5 ? * * *)",
        default: "cron(0 5 ? * * *)",
      },
      { key: "retentionDays", label: "Retention (days)", type: "number", default: 35 },
      {
        key: "coldStorageAfterDays",
        label: "Move to Cold After (days)",
        type: "number",
        placeholder: "90",
      },
    ],
    commonConnections: [
      { to: "ebs-volume", relationship: "reads_from", description: "Snapshots EBS volumes" },
      { to: "efs", relationship: "reads_from", description: "Backs up EFS file systems" },
      { to: "rds", relationship: "reads_from", description: "Backs up RDS databases" },
      { to: "dynamodb", relationship: "reads_from", description: "Backs up DynamoDB tables" },
    ],
  },
  {
    id: "s3-glacier",
    name: "S3 Glacier",
    fullName: "Amazon S3 Glacier",
    category: "storage",
    description: "Low-cost archive storage for long-term data retention and digital preservation.",
    icon: "❄️",
    scope: "region",
    cfnType: "AWS::Glacier::Vault",
    arnPattern: "arn:aws:glacier:{region}:{account}:vaults/{name}",
    keywords: ["glacier", "archive", "cold", "vault", "long-term"],
    configFields: [
      {
        key: "vaultName",
        label: "Vault Name",
        type: "string",
        placeholder: "archive-vault",
        required: true,
      },
      {
        key: "storageClass",
        label: "Storage Class",
        type: "select",
        default: "GLACIER_FLEXIBLE",
        options: [
          { value: "GLACIER_IR", label: "Glacier Instant Retrieval" },
          { value: "GLACIER_FLEXIBLE", label: "Glacier Flexible Retrieval" },
          { value: "DEEP_ARCHIVE", label: "Glacier Deep Archive" },
        ],
      },
      {
        key: "retrievalTier",
        label: "Retrieval Tier",
        type: "select",
        default: "Standard",
        options: [
          { value: "Expedited", label: "Expedited" },
          { value: "Standard", label: "Standard" },
          { value: "Bulk", label: "Bulk" },
        ],
      },
    ],
    commonConnections: [
      {
        to: "s3-bucket",
        relationship: "connects_to",
        description: "Archive tier for S3 lifecycle data",
      },
      { to: "kms", relationship: "depends_on", description: "Encryption key for archives" },
    ],
  },
];

export default storage;
